"""Add MedicineCatalog and batch fields

Revision ID: 2ee657e33329
Revises: e36108837c5b
Create Date: 2026-06-18 17:25:44.505326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee657e33329'
down_revision: Union[str, Sequence[str], None] = 'e36108837c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_catalog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('medicine_name', sa.String(), nullable=False),
    sa.Column('pack_size_label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_catalog_medicine_name'), 'medicine_catalog', ['medicine_name'], unique=False)
    op.add_column('medicine_batches', sa.Column('medicine_type', sa.String(), nullable=True))
    op.add_column('medicine_batches', sa.Column('pack_size', sa.String(), nullable=True))
    op.add_column('medicine_batches', sa.Column('number_of_packs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine_batches', 'number_of_packs')
    op.drop_column('medicine_batches', 'pack_size')
    op.drop_column('medicine_batches', 'medicine_type')
    op.drop_index(op.f('ix_medicine_catalog_medicine_name'), table_name='medicine_catalog')
    op.drop_table('medicine_catalog')
    # ### end Alembic commands ###
