"""Add requested_by

Revision ID: 5b0285ff51d6
Revises: 7e912e6d9f06
Create Date: 2026-06-20 22:53:24.091617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0285ff51d6'
down_revision: Union[str, Sequence[str], None] = '7e912e6d9f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_partnerships', sa.Column('requested_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_partnerships', 'requested_by')
    # ### end Alembic commands ###
