"""Add signature to handoff record

Revision ID: 7e912e6d9f06
Revises: e36e66986155
Create Date: 2026-06-19 21:52:15.592988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e912e6d9f06'
down_revision: Union[str, Sequence[str], None] = 'e36e66986155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handoff_records', sa.Column('signature', sa.Text(), nullable=True))
    op.add_column('handoff_records', sa.Column('public_key_pem', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handoff_records', 'public_key_pem')
    op.drop_column('handoff_records', 'signature')
    # ### end Alembic commands ###
