"""Add pieces_per_pack and pack_size_label

Revision ID: 95214cbe6732
Revises: 2ee657e33329
Create Date: 2026-06-18 18:02:42.185993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95214cbe6732'
down_revision: Union[str, Sequence[str], None] = '2ee657e33329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_batches', sa.Column('pieces_per_pack', sa.Integer(), nullable=True))
    op.add_column('stock_levels', sa.Column('pieces_per_pack', sa.Integer(), nullable=True))
    op.add_column('stock_levels', sa.Column('pack_size_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_levels', 'pack_size_label')
    op.drop_column('stock_levels', 'pieces_per_pack')
    op.drop_column('medicine_batches', 'pieces_per_pack')
    # ### end Alembic commands ###
