"""add ecdsa keypair columns to users

Revision ID: 97cd2e3cc208
Revises: 50b76fa2d6b6
Create Date: 2026-06-12 17:19:06.561825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cd2e3cc208'
down_revision: Union[str, Sequence[str], None] = '50b76fa2d6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_key_pem', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('private_key_pem', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'private_key_pem')
    op.drop_column('users', 'public_key_pem')
    # ### end Alembic commands ###
