"""add zkp and ecdsa columns

Revision ID: e36108837c5b
Revises: 97cd2e3cc208
Create Date: 2026-06-12 17:29:12.852099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36108837c5b'
down_revision: Union[str, Sequence[str], None] = '97cd2e3cc208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_logs', sa.Column('signature', sa.Text(), nullable=True))
    op.add_column('approval_logs', sa.Column('signer_address', sa.String(), nullable=True))
    op.add_column('handoff_records', sa.Column('quantity_commitment', sa.String(), nullable=True))
    op.add_column('handoff_records', sa.Column('quantity_salt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handoff_records', 'quantity_salt')
    op.drop_column('handoff_records', 'quantity_commitment')
    op.drop_column('approval_logs', 'signer_address')
    op.drop_column('approval_logs', 'signature')
    # ### end Alembic commands ###
