"""Add TradePartnership

Revision ID: e36e66986155
Revises: eab951bc6977
Create Date: 2026-06-18 20:33:06.226034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36e66986155'
down_revision: Union[str, Sequence[str], None] = 'eab951bc6977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_partnerships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_entity_id', sa.String(), nullable=False),
    sa.Column('to_entity_id', sa.String(), nullable=False),
    sa.Column('from_entity_type', sa.String(), nullable=False),
    sa.Column('to_entity_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('latency_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_partnerships')
    # ### end Alembic commands ###
