"""multi_sig_admin_override

Revision ID: eab951bc6977
Revises: 95214cbe6732
Create Date: 2026-06-18 19:21:24.413738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab951bc6977'
down_revision: Union[str, Sequence[str], None] = '95214cbe6732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_override_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('initiated_by', sa.String(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('current_approvals', sa.Integer(), nullable=True),
    sa.Column('override_blockchain_hash', sa.String(), nullable=True),
    sa.Column('ai_cross_check', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_override_votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('override_request_id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('admin_name', sa.String(), nullable=False),
    sa.Column('admin_sub_role', sa.String(), nullable=False),
    sa.Column('vote', sa.String(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['override_request_id'], ['admin_override_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shipments', sa.Column('override_blockchain_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'override_blockchain_hash')
    op.drop_table('admin_override_votes')
    op.drop_table('admin_override_requests')
    # ### end Alembic commands ###
